apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elastic
spec:
  ports:
  - name: first-port
    port: 9200
    targetPort: 9200
  - name: second-port
    port: 9300
    targetPort: 9300
  selector:
    app: elastic
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
    spec:
      volumes:
      - name: elastic-volume
        persistentVolumeClaim:
          claimName: pvc-nfs-worker
      containers:
      - name: elasticsearch-6-8-0
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        volumeMounts:
        - name: elastic-volume
          mountPath: /mnt
        env:
        - name: ES_JAVA_OPT
          value: "-Xms2g -Xms2g"
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
        - containerPort: 9300
