apiVersion: v1
kind: Service
metadata:
  name: nats-server
  labels:
    app: nats
spec:
  ports:
  - name: client-port
    port: 4222
    targetPort: 4222
  - name: management-port
    port: 8222
    targetPort: 8222
  - name: routing-port
    port: 6222
    targetPort: 6222
  selector:
    app: nats-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats
        ports:
        - containerPort: 4222
        - containerPort: 8222
        - containerPort: 6222
