apiVersion: v1
kind: Service
metadata:
  name: hotrod
  labels:
    app: hot
spec:
  ports:
  - name: port-8080
    port: 8080
    targetPort: 8080
  - name: port-8081
    port: 8081
    targetPort: 8081
  - name: port-8082
    port: 8082
    targetPort: 8082
  - name: port-8083
    port: 8083
    targetPort: 8083
  selector:
    app: hot
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
spec:
  selector:
    matchLabels:
      app: hot
  replicas: 1
  template:
    metadata:
      labels:
        app: hot
    spec:
      volumes:
      - name: hotrod-volume
        persistentVolumeClaim:
          claimName: pvc-nfs-worker
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:latest
        env:
        - name: JAEGER_AGENT_HOST
          value: "10.107.197.168"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        volumeMounts:
        - name: hotrod-volume
          mountPath: /mnt
        ports:
        - containerPort: 8080
          name: port-8080
        - containerPort: 8081
          name: port-8081
        - containerPort: 8082
          name: port-8082
        - containerPort: 8083
          name: port-8083
