apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-master
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 128.110.154.167
    path: /users/labor/kofiffo/onlab2/nfs
